#!/usr/bin/env bash
#Configure a new Nginx server so that /redirect_me is redirecting to another page

# Upadating Packages
sudo apt-get -y update
sudo apt-get -y install nginx

# Create index.html page
echo "Hello World" | sudo tee /var/www/html/index

string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/besthor permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart
