#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers

sudo apt-get -y update
sudo apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  Amirametwally_frontend
        bind *:80
        mode http
        default_backend Amirametwally_backend
backend Amirametwally_backend
        balance roundrobin
        server 478090-web-01 54.237.99.66:80 check
        server 478090-web-02 34.202.159.136:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

sudo service haproxy restart
