#!/usr/bin/env bash
# Bash script that configures the container
chmod 777 /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/site-available/default
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
pkill -9 apache
su nginx -c "service nginx restart"
